# Generated by Django 5.2.5 on 2025-08-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("apellidos", models.CharField(max_length=200)),
                ("domicilio", models.CharField(max_length=500)),
                ("fecha", models.DateField()),
                ("modalidad", models.CharField(max_length=2)),
                ("padre", models.CharField(max_length=100)),
                ("madre", models.CharField(max_length=100)),
                ("telPadre", models.CharField(max_length=15)),
                ("telMadre", models.CharField(max_length=15)),
                ("correo", models.CharField(max_length=100)),
                ("cuenta", models.CharField(max_length=100)),
            ],
        ),
    ]
