# Generated by Django 5.2.5 on 2025-08-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inscripcion",
            name="modalidad",
            field=models.IntegerField(
                choices=[
                    (1, "Iniciación/extraescolar"),
                    (2, "Competición 2 días"),
                    (3, "Competición 3 días"),
                    (4, "Grupo Show (1 hora semanal)"),
                ],
                default=2,
            ),
        ),
    ]
