# Generated by Django 5.2.5 on 2025-08-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0002_alter_inscripcion_modalidad"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscripcion",
            name="grupoShow",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="inscripcion",
            name="modalidad",
            field=models.IntegerField(
                choices=[
                    (1, "Iniciación/extraescolar"),
                    (2, "Competición 2 días"),
                    (3, "Competición 3 días"),
                ],
                default=2,
            ),
        ),
    ]
